#
# Device trackers
#
# @link https://home-assistant.io/components/device_tracker/
#


#
# Bluetooth
#
# https://home-assistant.io/components/device_tracker.bluetooth_tracker/
#
- platform: bluetooth_tracker
  request_rssi: true
  track_new_devices: true
