#
# Device trackers
#
# @link https://www.home-assistant.io/integrations/device_tracker/
#


#
# Bluetooth
#
# https://www.home-assistant.io/integrations/bluetooth_tracker/
#
- platform: bluetooth_tracker
  request_rssi: true
  track_new_devices: true


#
# Ping
#
# https://www.home-assistant.io/integrations/ping/
#
- platform: ping
  count: 2
  hosts:
    kiosk_ping: !secret fully_kiosk_host
