#
# Media players
#
# @link https://home-assistant.io/components/media_player/
#


#
# Kodi
#
# @link https://kodi.tv/
# @link https://home-assistant.io/components/media_player.kodi/
#
- platform: kodi
  name: Kodi
  host: !secret kodi_host
  port: !secret kodi_port
  tcp_port: !secret kodi_tcp_port
  username: !secret kodi_username
  password: !secret kodi_password
  enable_websocket: true
