#
# Scenes
#
# @link https://www.home-assistant.io/integrations/scene/
#


#
# LIFX cloud scenes
#
# @see /misc/lifx.yaml
#
# @link https://api.developer.lifx.com/docs/list-scenes
# @link https://www.home-assistant.io/integrations/lifx_cloud/
#
- platform: lifx_cloud
  token: !secret lifx_cloud_token
  timeout: 10
