#
# LANnouncer notification service for local Android devices
#
# @link http://www.keybounce.com/lannouncer/
# @link https://www.home-assistant.io/integrations/lannouncer/
#
- platform: lannouncer
  name: "LANnouncer"
  host: !secret lannouncer_host
  port: !secret lannouncer_port
