#
# Automations
#
# @link https://www.home-assistant.io/integrations/automation/
#
automation: !include_dir_merge_list automations/


#
# Binary sensors
#
# @link https://www.home-assistant.io/integrations/binary_sensor/
#
binary_sensor: !include misc/binary_sensors.yaml


#
# Brother Printer
#
# Reads current data from your local Brother printer.
#
# @link https://www.home-assistant.io/integrations/brother/
#
brother:

#
# Browser mod
#
# Turns web browsers into controllable entities.
#
# @link https://github.com/thomasloven/hass-browser_mod
#
browser_mod:
  prefix: "browser_"


#
# Cameras
#
# @link https://www.home-assistant.io/integrations/camera/
#
camera: !include_dir_merge_list cameras/


#
# Enable the configuration UI
#
# @link https://www.home-assistant.io/integrations/config/
#
config:


#
# Allow you to issue voice commands from the frontend in enabled browsers
#
# @link https://www.home-assistant.io/integrations/conversation/
#
# conversation:


#
# Counters
#
# @link https://www.home-assistant.io/integrations/counter/
#
counter: !include misc/counters.yaml


#
# Home Assistant Community Store
#
# @link https://hacs.xyz/
#
hacs:
  token: !secret github_access_token


#
# Device trackers
#
# @link https://www.home-assistant.io/integrations/device_tracker/
#
device_tracker: !include misc/device_trackers.yaml


#
# Discover some devices automatically
#
# @link https://www.home-assistant.io/integrations/discovery/
#
discovery:
  ignore:
    - google_cast
    - samsung_printer


#
# Displays
#
# @see /custom_components/display/
#
# @link https://github.com/daemondazz/homeassistant-displays
#
display: !include misc/displays.yaml


#
# Enable the official UI
#
# @link https://www.home-assistant.io/integrations/frontend/
#
frontend:
  themes: !include_dir_named themes/


#
# Combine entities into groups
#
# @link https://www.home-assistant.io/integrations/group/
#
group: !include misc/groups.yaml


#
# Enable the Hass.io panel
#
# @link https://www.home-assistant.io/hassio/
#
hassio:


#
# Enable support for tracking state changes over time
#
# @link https://www.home-assistant.io/integrations/history/
#
history:


#
# Setup basic Home Assistant information
#
# @link https://www.home-assistant.io/docs/configuration/basic/
#
homeassistant:
  name: !secret homeassistant_name
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
  whitelist_external_dirs:
    - !secret homeassistant_whitelist_config
    - !secret homeassistant_whitelist_share


#
# HomeKit
#
# @link https://www.home-assistant.io/integrations/homekit/
#
homekit: !include misc/homekit.yaml


#
# Enable the web server
#
# `cors_allowed_origins` includes the domain:port for AppDaemon.
#
# @link https://www.home-assistant.io/integrations/http/
#
http:
  server_port: !secret http_server_port
  cors_allowed_origins: !secret http_cors_allowed_origins


#
# IFTTT integration
#
# @link https://www.home-assistant.io/integrations/ifttt/
#
ifttt:
  key: !secret ifttt_key


#
# Input booleans
#
# @link https://www.home-assistant.io/integrations/input_boolean/
#
input_boolean: !include inputs/input_booleans.yaml


#
# Input datetimes
#
# @link https://www.home-assistant.io/integrations/input_datetime/
#
input_datetime: !include inputs/input_datetimes.yaml


#
# Lists of selectable values
#
# @link https://www.home-assistant.io/integrations/input_select/
#
input_select: !include inputs/input_selects.yaml


#
# iOS companion component for the  Home Assistant iOS app
#
# @link https://itunes.apple.com/us/app/home-assistant-open-source-home-automation/id1099568401
# @link https://companion.home-assistant.io/
#
ios:


#
# LIFX
#
# @link https://www.home-assistant.io/integrations/lifx/
#
lifx: !include misc/lifx.yaml


#
# Lights
#
# @link https://www.home-assistant.io/integrations/light/
#
light: !include_dir_merge_list lights/


#
# Local IP address
#
# @link https://www.home-assistant.io/integrations/local_ip/
#
local_ip:


#
# View all events in a logbook
#
# @link https://www.home-assistant.io/integrations/logbook/
#
logbook:


#
# Log some details
#
# @link https://www.home-assistant.io/integrations/logger/
#
logger:
  default: warning
  logs:
    aiohttp.server: critical # EBOX newer component bug.
    custom_components.display: critical # When tablet is offline.
    custom_components.gtfs_custom: critical # Until GTFS integration overhaul is complete
    custom_components.light.lightpack: critical # When Lightpack is offline.
    homeassistant.components.unifi: fatal # When Unifi Controller is temporarily unreachable.
    homeassistant.components.media_player.plex: fatal # When Plex is offline.
    sqlalchemy.exc: critical # Until GTFS integration overhaul is complete
    sqlalchemy.exc.ProgrammingError: critical # Until GTFS integration overhaul is complete
    homeassistant.helpers.entity: critical # Until GTFS integration overhaul is complete
    pyunifi.controller: error # When Unifi Controller is temporarily unreachable.


#
# Lovelace user interface
#
# @link https://www.home-assistant.io/lovelace/
#
lovelace:
  mode: yaml
  resources: !include misc/lovelace_resources.yaml


#
# Enable a map showing the location of tracked devices
#
# @link https://www.home-assistant.io/integrations/map/
#
map:


#
# Media players
#
# @link https://www.home-assistant.io/integrations/media_player/
#
media_player: !include misc/media_players.yaml


#
# Mobile companion app
#
# @link https://companion.home-assistant.io/
# @link https://www.home-assistant.io/integrations/mobile_app/
#
mobile_app:


#
# MQTT Integration
#
# @link https://www.home-assistant.io/integrations/mqtt/
#
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: home-assistant
  birth_message:
    topic: "hass/status"
    payload: "online"
  will_message:
    topic: "hass/status"
    payload: "offline"


#
# Notification services
#
# @link https://www.home-assistant.io/integrations/notify/
#
notify: !include_dir_merge_list notifications/


#
# Person presence detection
#
# @link https://www.home-assistant.io/integrations/person/
#
person: !include misc/persons.yaml


#
# Database recorder
#
# Limit the number of tracked entities and length of history.
#
# @link https://www.home-assistant.io/integrations/recorder/
#
recorder: !include misc/recorder.yaml


#
# Scenes
#
# @link https://www.home-assistant.io/integrations/scene/
#
scene: !include misc/scenes.yaml


#
# Scripts
#
# @link https://www.home-assistant.io/integrations/script/
#
script: !include_dir_named scripts/


#
# Sensors
#
# @link https://www.home-assistant.io/integrations/sensor/
#
sensor: !include_dir_merge_list sensors/


#
# Shell commands
#
# @link https://www.home-assistant.io/integrations/shell_command/
#
shell_command: !include misc/shell_commands.yaml


#
# Speedtest.net
#
# @link https://www.home-assistant.io/integrations/speedtestdotnet/
#
speedtestdotnet: !include misc/speedtest.yaml


#
# Track the sun
#
# @link https://www.home-assistant.io/integrations/sun/
#
sun:


#
# Switches
#
# @link https://www.home-assistant.io/integrations/switch/
#
switch: !include_dir_merge_list switches/


#
# System health
#
# @link https://www.home-assistant.io/integrations/system_health/
#
system_health:


#
# TP-Link Kasa Smart
#
# @link https://www.home-assistant.io/integrations/tplink/
#
tplink: !include misc/tplink.yaml


#
# Text-to-Speech
#
# @link https://www.home-assistant.io/integrations/tts/
#
tts:
  - platform: google_translate


#
# Check for available updates
#
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# Optionally allow Home Assistant developers to focus on popular components.
#
# @link https://www.home-assistant.io/blog/2016/10/25/explaining-the-updater/
# @link https://www.home-assistant.io/integrations/updater/
#
updater:
  include_used_components: true


#
# Variables
#
# @see /custom_components/variable.py
#
# @link https://github.com/rogro82/hass-variables
#
variable: !include inputs/variables.yaml



#
# Weather
#
# @link https://www.home-assistant.io/integrations/weather/
#
weather: !include misc/weather.yaml


#
# Zones
#
# @link https://www.home-assistant.io/integrations/zone/
#
zone: !include misc/zones.yaml


#
# Z-Wave integration
#
# @link https://www.home-assistant.io/docs/z-wave/adding/
# @link https://www.home-assistant.io/docs/z-wave/
# @link https://www.home-assistant.io/integrations/zwave/
#
zwave:
  device_config: !include zwave_device_config.yaml
  network_key: !secret zwave_network_key
  usb_path: /dev/ttyACM0
