#
# Atomations
#
# @link https://home-assistant.io/components/automation/
#
#automation: !include_dir_merge_list automations/


#
# Binary sensors
#
# @link https://home-assistant.io/components/binary_sensor/
#
#binary_sensor: !include misc/binary_sensors.yaml


#
# Cameras
#
# @link https://home-assistant.io/components/camera/
#
#camera: !include_dir_merge_list cameras/


#
# Enable the configuration UI
#
# @link https://home-assistant.io/components/config/
#
config:


#
# Allow you to issue voice commands from the frontend in enabled browsers
#
# @link https://home-assistant.io/components/conversation/
#
# conversation:


#
# Counters
#
# @link https://www.home-assistant.io/components/counter/
#
counter: !include misc/counters.yaml


#
# Custom Updater
#
# @link https://github.com/custom-components/custom_updater/
#
#custom_updater: !include misc/custom_updater.yaml


#
# Enable the UI customizer
#
# @link https://github.com/andrey-git/home-assistant-customizer
#
# customizer:
#   custom_ui: local


#
# Device trackers
#
# @link https://home-assistant.io/components/device_tracker/
#
#device_tracker: !include misc/device_trackers.yaml


#
# Discover some devices automatically
#
# @link https://home-assistant.io/components/discovery/
#
#discovery:
#  ignore:
#    - google_cast
#    - samsung_printer


#
# Displays
#
# @see /custom_components/display/
#
# @link https://github.com/daemondazz/homeassistant-displays
#
#display: !include misc/displays.yaml


#
# Enable the official UI
#
# @link https://home-assistant.io/components/frontend/
#
frontend:
  # javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-value_only.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
    - /local/custom_ui/state-card-hline.html
    - /local/custom_ui/state-card-value_only.html
  themes: !include_dir_named themes/


#
# Combine entities into groups and organize UI
#
# @link https://home-assistant.io/components/group/
#
#group: !include_dir_merge_named groups/


#
# Enable the Hass.io panel
#
# @link https://www.home-assistant.io/hassio/
#
#hassio:


#
# Enable support for tracking state changes over time
#
# @link https://home-assistant.io/components/history/
#
history:


#
# Setup basic Home Assistant information
#
homeassistant:
  name: Home
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude
  elevation: !secret zone_home_elevation
  unit_system: metric
  time_zone: !secret homeassistant_time_zone
  customize_glob: !include customize_glob.yaml
  customize: !include customize.yaml
  whitelist_external_dirs:
    - !secret homeassistant_whitelist_config


#
# HomeKit
#
# @link https://www.home-assistant.io/components/homekit/
#
#homekit: !include misc/homekit.yaml


#
# Enable the web server
#
# `cors_allowed_origins` includes the domain:port for AppDaemon.
#
# @link https://home-assistant.io/components/http/
#
http:
#  api_password: !secret http_password
  base_url: !secret http_base_url
  server_port: !secret http_server_port
  cors_allowed_origins: !secret http_cors_allowed_origins


#
# IFTTT integration
#
# @link https://home-assistant.io/components/ifttt/
#
# ifttt:
#   key: !secret ifttt_key


#
# Input booleans
#
# @link https://home-assistant.io/components/input_boolean/
#
#input_boolean: !include misc/input_booleans.yaml


#
# Lists of selectable values
#
# @link https://home-assistant.io/components/input_select/
#
#input_select: !include misc/input_selects.yaml


#
# iOS companion component for the  Home Assistant iOS app
#
# @link https://itunes.apple.com/us/app/home-assistant-open-source-home-automation/id1099568401
# @link https://home-assistant.io/docs/ecosystem/ios/
#
#ios:


#
# LIFX
#
# @link https://www.home-assistant.io/components/lifx/
#
#lifx: !include misc/lifx.yaml



#
# Lights
#
# @link https://home-assistant.io/components/light/
#
#light: !include_dir_merge_list lights/


#
# View all events in a logbook
#
# @link https://home-assistant.io/components/logbook/
#
# logbook:


#
# Log some details
#
# @link https://home-assistant.io/components/logger/
#
logger:
  default: warning
  logs:
    aiohttp.server: critical # EBOX newer component bug.
    custom_components.display: critical # When tablet is offline.
    custom_components.gtfs.sensor: debug
    custom_components.lightpack.light: critical # When Lightpack is offline.
    homeassistant.components.unifi.device_tracker: fatal # When Unifi Controller is temporarily unreachable.
    homeassistant.components.plex.media_player: fatal # When Plex is offline.
    homeassistant.components.tplink.switch: error # When switch is unplugged.
    pyunifi.controller: error # When Unifi Controller is temporarily unreachable.


#
# Lovelace interface
#
# @link https://www.home-assistant.io/lovelace/
#
lovelace:
  mode: yaml


#
# Enable a map showing the location of tracked devices
#
# @link https://home-assistant.io/components/map/
#
# map:


#
# Media players
#
# @link https://home-assistant.io/components/media_player/
#
#media_player: !include misc/media_players.yaml


#
# MQTT Integration
#
# @link https://home-assistant.io/components/mqtt/
#
#mqtt:
#  broker: !secret mqtt_broker
#  port: !secret mqtt_port
#  username: !secret mqtt_username
#  password: !secret mqtt_password
#  client_id: home-assistant
#  birth_message:
#    topic: 'hass/status'
#    payload: 'online'
#  will_message:
#    topic: 'hass/status'
#    payload: 'offline'


#
# Notification services
#
# @link https://home-assistant.io/components/notify/
#
#notify: !include_dir_merge_list notifications/


#
# Database recorder
#
# Limit the number of tracked entities and length of history.
#
# @link https://home-assistant.io/components/recorder/
#
recorder: !include misc/recorder.yaml


#
# Scenes
#
# @link https://home-assistant.io/components/scene/
#
#scene: !include misc/scenes.yaml


#
# Scripts
#
# @link https://home-assistant.io/components/script/
#
#script: !include_dir_named scripts/


#
# Sensors
#
# @link https://home-assistant.io/components/sensor/
#
#sensor: !include_dir_merge_list sensors/
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'time_date'
  - platform: version
  - platform: gtfs
#    name: 'Home to Metro'
    origin: !secret gtfs_origin_1
    destination: !secret gtfs_destination_1
    data: !secret gtfs_data
    include_tomorrow: true
    departures:
      - 0
      - 1
      - 2
      - 3
#    offset: 3600
#    scan_interval: 60
#
#  - platform: gtfs
#    origin: !secret gtfs_origin_1
#    destination: !secret gtfs_destination_1
#    data: !secret gtfs_data
#    include_tomorrow: true

#
# Shell commands
#
# @link https://home-assistant.io/components/shell_command/
#
#shell_command: !include misc/shell_commands.yaml


#
# Speedtest.net
#
# @link https://home-assistant.io/components/speedtestdotnet/
#
#speedtestdotnet: !include misc/speedtest.yaml


#
# Track the sun
#
# @link https://home-assistant.io/components/sun/
#
sun:


#
# Switches
#
# @link https://home-assistant.io/components/switch/
#
#switch: !include_dir_merge_list switches/


#
# System health
#
# @link https://home-assistant.io/components/system_health/
#
system_health:


#
# Text to speech
#
# @link https://home-assistant.io/components/tts/
#
#tts:
#  - platform: google


#
# Check for available updates
#
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# Optionally allow Home Assistant developers to focus on popular components.
#
# @link https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
# @link https://home-assistant.io/components/updater/
#
#updater:
#  include_used_components: true


#
# Variables
#
# @see /custom_components/variable.py
#
# @link https://github.com/rogro82/hass-variables
#
#variable: !include misc/variables.yaml



#
# Weather
#
# @link https://www.home-assistant.io/components/weather/
#
#weather: !include misc/weather.yaml


#
# Zones
#
# @link https://home-assistant.io/components/zone/
#
#zone: !include misc/zones.yaml


#
# ZWave integration
#
# @link https://home-assistant.io/docs/z-wave/adding/
# @link https://home-assistant.io/docs/z-wave/
# @link https://home-assistant.io/components/zwave/
#
#zwave:
#  usb_path: /dev/ttyACM0
#  network_key: !secret zwave_network_key
