#
# Light switches
#
# Assign existing switches as lights.
#
# @see /switches/
#
# @link https://www.home-assistant.io/integrations/light.switch/
#
- platform: switch
  name: "Bedside"
  entity_id: switch.bedside_light

- platform: switch
  name: "Nightstand"
  entity_id: switch.nightstand_light

- platform: switch
  name: "Rope"
  entity_id: switch.rope_light

- platform: switch
  name: "Souvenirs"
  entity_id: switch.souvenirs_light

- platform: switch
  name: "Window"
  entity_id: switch.window_light
