#
# EBOX.ca ISP bandwidth usage
#
# @see /custom_components/ebox/sensor.py
#
# @link https://client.ebox.ca/
# @link https://www.home-assistant.io/integrations/ebox/
#
- platform: ebox
  username: !secret ebox_username
  password: !secret ebox_password
  scan_interval: 3600
  monitored_variables:
   - before_offpeak_download
   - before_offpeak_upload
   - download
   - limit
   - usage

- platform: template
  sensors:
    ebox_download_before_offpeak_rounded:
      friendly_name_template: >
        {{ state_attr('sensor.ebox_download_before_offpeak', 'friendly_name') }}
      icon_template: >
        {{ state_attr('sensor.ebox_download_before_offpeak', 'icon') }}
      unit_of_measurement: 'Gb'
      value_template: >-
        {{ states('sensor.ebox_download_before_offpeak') | round }}

    ebox_download_remaining:
      friendly_name: "Remaining Downloads"
      icon_template: "mdi:briefcase-download"
      unit_of_measurement: 'Gb'
      value_template: >-
        {% set limit = states('sensor.ebox_data_limit') | float(-1) %}
        {% set download = states('sensor.ebox_download_before_offpeak') | float(-1) %}

        {% if limit == 0 %}
          ∞
        {% elif limit > 0 and download >= 0 %}
          {{ (limit - download) | int }}
        {% else %}
          unknown
        {% endif %}

    ebox_download_daily_capacity:
      friendly_name: "Daily Capacity"
      icon_template: "mdi:speedometer"
      unit_of_measurement: 'Gb'
      value_template: >-
        {% set days = states('sensor.days_remaining_in_month') | int(-1) %}
        {% set download = states('sensor.ebox_download_remaining') %}

        {% if download == '∞' %}
          ∞
        {% elif download == 'unknown' or days < 0 %}
          unknown
        {% elif download|float > 0 and days > 0 %}
          {{ (download|float / days) | int }}
        {% else %}
          0
        {% endif %}

    ebox_upload_before_offpeak_rounded:
      friendly_name_template: >
        {{ state_attr('sensor.ebox_upload_before_offpeak', 'friendly_name') }}
      icon_template: >
        {{ state_attr('sensor.ebox_upload_before_offpeak', 'icon') }}
      unit_of_measurement: 'Gb'
      value_template: >-
        {{ states('sensor.ebox_upload_before_offpeak') | round }}

    ebox_upload_remaining:
      friendly_name: "Remaining Uploads"
      icon_template: "mdi:briefcase-upload"
      unit_of_measurement: 'Gb'
      value_template: >-
        {% set limit = states('sensor.ebox_data_limit') | float(-1) %}
        {% set upload = states('sensor.ebox_upload_before_offpeak') | float(-1) %}

        {% if limit == 0 %}
          ∞
        {% elif limit > 0 and upload >= 0 %}
          {{ (limit - upload) | int }}
        {% else %}
          unknown
        {% endif %}

    ebox_usage_friendly:
      friendly_name: "Monthly Usage"
      icon_template: "mdi:percent"
      unit_of_measurement: '%'
      value_template: >-
        {{ states('sensor.ebox_usage') | round }}


#
# Speedtest.net network speed testing
#
# https://www.home-assistant.io/integrations/speedtestdotnet/
#
- platform: template
  sensors:
    speedtest_ping_rounded:
      friendly_name: "Ping"
      icon_template: "mdi:timer"
      unit_of_measurement: 'ms'
      value_template: >-
        {{ states('sensor.speedtest_ping') | round }}

    speedtest_download_rounded:
      friendly_name: "Downspeed"
      icon_template: "mdi:download-network"
      unit_of_measurement: 'Mbit/s'
      value_template: >-
        {{ states('sensor.speedtest_download') | round }}

    speedtest_upload_rounded:
      friendly_name: "Upspeed"
      icon_template: "mdi:upload-network"
      unit_of_measurement: 'Mbit/s'
      value_template: >-
        {{ states('sensor.speedtest_upload') | round }}
