#
# Radar maps of surrounding precipitation conditions (last 2 hours)
#
# @see /appdaemon/dashboards/Weather.dash
#
# @link https://www.home-assistant.io/integrations/environment_canada/
# @link https://weather.gc.ca/radar/
#
- platform: environment_canada
  name: "Environment Canada"
  station: !secret environment_canada_radar
  loop: true
